/* eslint-disable */
//               name,   op,       tex_op,     graphic  op_num  notation            num
OPERATION_HANDLE(SUM,    "+",      "+",        "+",     2,      OP_NOTATION_MIDDLE, 0)        
OPERATION_HANDLE(SUB,    "-",      "-",        "-",     2,      OP_NOTATION_MIDDLE, 1)    
OPERATION_HANDLE(MUL,    "*",      "\\cdot",   "*",     2,      OP_NOTATION_MIDDLE, 2)    
OPERATION_HANDLE(DIV,    "/",      "\\frac",   "/",     2,      OP_NOTATION_LEFT,   3)
OPERATION_HANDLE(POW,    "^",      "^",        "^",     2,      OP_NOTATION_MIDDLE, 4)    
OPERATION_HANDLE(SIN,    "sin",    "\\sin",    "sin",   1,      OP_NOTATION_LEFT,   5)
OPERATION_HANDLE(COS,    "cos",    "\\cos",    "cos",   1,      OP_NOTATION_LEFT,   6)
OPERATION_HANDLE(TG,     "tg",     "\\tan",    "tan",   1,      OP_NOTATION_LEFT,   7)
OPERATION_HANDLE(CTG,    "ctg",    "\\cot",    "cot",   1,      OP_NOTATION_LEFT,   8)
OPERATION_HANDLE(ARCSIN, "arcsin", "\\arcsin", "asin",  1,      OP_NOTATION_LEFT,   9)
OPERATION_HANDLE(ARCCOS, "arccos", "\\arccos", "acos",  1,      OP_NOTATION_LEFT,   10)
OPERATION_HANDLE(ARCTG,  "arctg",  "\\arctan", "atan",  1,      OP_NOTATION_LEFT,   11)
OPERATION_HANDLE(ARCCTG, "arcctg", "\\arccot", "acot",  1,      OP_NOTATION_LEFT,   12)
OPERATION_HANDLE(SH,     "sh",     "\\sinh",   "sinh",  1,      OP_NOTATION_LEFT,   13)
OPERATION_HANDLE(CH,     "ch",     "\\cosh",   "cosh",  1,      OP_NOTATION_LEFT,   14)
OPERATION_HANDLE(TH,     "th",     "\\tanh",   "tanh",  1,      OP_NOTATION_LEFT,   15)
OPERATION_HANDLE(CTH,    "cth",    "\\coth",   "coth",  1,      OP_NOTATION_LEFT,   16)
OPERATION_HANDLE(LOG,    "log",    "\\log_",   "log_",  2,      OP_NOTATION_LEFT,   17)
OPERATION_HANDLE(LN,     "ln",     "\\ln",     "log",   1,      OP_NOTATION_LEFT,   18)