<start> ::= <sum> "$"
<sum> ::= <mul> (("+" | "-") <mul>)*
<mul> ::= <func> (("*" | "/") <func>)*

<func> ::= <binary_func> | <unary_func> | <pow>
<binary_func> ::= 
    <binary_func_names> 
        "{" <sum> "}"
        "{" <sum> "}" 
<unary_func> ::= <unary_func_names> <func>
<unary_func_names> ::= 
    "sin" | "cos " | "tg" | "ctg" | 
    "arcsin" | "arccos" | "arctg" | "arcctg" |
    "sh" | "ch" | "th" | "cth"
<binary_func_names> ::= "log"

<pow> ::= <brakets> ("^" <pow>)*

<brakets> ::= "(" <sum> ")" | <num_var>
<num_var> ::= <double> | <var>
<double> ::= "e" | "-"? <uint> ("." [0-9]*)?
<uint> ::= "0" | [1-9] [0-9]*
<var> ::= [a-d] | [f-z]
