<start> ::= <sum> "$"
<sum> ::= <mul> (("+" | "-") <mul>)*
<mul> ::= <pow> (("*" | "/") <pow>)*
<pow> ::= <brakets> ("^" <brakets>)*
<brakets> ::= "(" <sum> ")" | <num_var>
<num_var> ::= <double> | <var>
<double> ::= "e" | "-"? <uint> ("." [0-9]*)?
<uint> ::= "0" | [1-9] [0-9]*
<var> ::= [a-d] | [f-z]